### ISSUE TITLE
Something weird with the %page placeholder

### ISSUE THREAD

**Issue by Plou** [Inouit/dummy#52]
It adds margin to the existing padding, which is weird on small device.
I think it is an attempt to replace padding with margins, but I don't remember what's the benefit of it. Anyway, it miss at least a `padding: 0;` in the media query.

```scss
%page {
  margin: auto; padding: 0 $page-padding*1px; width: $max-width; max-width: 100%;

  @media screen and (max-width: $max-width+($page-padding*2px)) { margin-right: ($page-padding*1px); margin-left: ($page-padding*1px); width: auto; }
}
```
